In [1]:
!pip install kagglehub pandas numpy matplotlib seaborn scikit-learn

Requirement already satisfied: kagglehub in d:\college\own\ml\scs\.venv\lib\site-packages (1.0.2)
Requirement already satisfied: pandas in d:\college\own\ml\scs\.venv\lib\site-packages (3.0.6)
Requirement already satisfied: numpy in d:\college\own\ml\scs\.venv\lib\site-packages (2.5.3)
Requirement already satisfied: matplotlib in d:\college\own\ml\scs\.venv\lib\site-packages (3.11.2)
Requirement already satisfied: seaborn in d:\college\own\ml\scs\.venv\lib\site-packages (0.13.2)
Requirement already satisfied: scikit-learn in d:\college\own\ml\scs\.venv\lib\site-packages (1.9.1)
Requirement already satisfied: kagglesdk<1.0,>=0.1.22 in d:\college\own\ml\scs\.venv\lib\site-packages (from kagglehub) (0.1.37)
Requirement already satisfied: packaging in d:\college\own\ml\scs\.venv\lib\site-packages (from kagglehub) (26.3)
Requirement already satisfied: pyyaml in d:\college\own\ml\scs\.venv\lib\site-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in d:\college\own\ml\scs\.venv\lib\site-packages (from kagglehub) (2.34.2)
Requirement already satisfied: tqdm in d:\college\own\ml\scs\.venv\lib\site-packages (from kagglehub) (4.70.1)
Requirement already satisfied: protobuf in d:\college\own\ml\scs\.venv\lib\site-packages (from kagglesdk<1.0,>=0.1.22->kagglehub) (7.36.2)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\college\own\ml\scs\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in d:\college\own\ml\scs\.venv\lib\site-packages (from pandas) (2026.4)
Requirement already satisfied: contourpy>=1.0.1 in d:\college\own\ml\scs\.venv\lib\site-packages (from matplotlib) (1.4.0)
Requirement already satisfied: cycler>=0.10 in d:\college\own\ml\scs\.venv\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in d:\college\own\ml\scs\.venv\lib\site-packages (from matplotlib) (4.66.0)
Requirement already satisfied: kiwisolver>=1.3.1 in d:\college\own\ml\scs\.venv\lib\site-packages (from matplotlib) (1.5.1)
Requirement already satisfied: pillow>=9 in d:\college\own\ml\scs\.venv\lib\site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in d:\college\own\ml\scs\.venv\lib\site-packages (from matplotlib) (3.3.3)
Requirement already satisfied: scipy>=1.10.0 in d:\college\own\ml\scs\.venv\lib\site-packages (from scikit-learn) (1.18.1)
Requirement already satisfied: joblib>=1.4.0 in d:\college\own\ml\scs\.venv\lib\site-packages (from scikit-learn) (1.6.0)
Requirement already satisfied: narwhals>=2.0.1 in d:\college\own\ml\scs\.venv\lib\site-packages (from scikit-learn) (2.26.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in d:\college\own\ml\scs\.venv\lib\site-packages (from scikit-learn) (3.7.0)
Requirement already satisfied: cloudpickle>=3.0 in d:\college\own\ml\scs\.venv\lib\site-packages (from joblib>=1.4.0->scikit-learn) (3.1.2)
Requirement already satisfied: six>=1.5 in d:\college\own\ml\scs\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in d:\college\own\ml\scs\.venv\lib\site-packages (from requests->kagglehub) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in d:\college\own\ml\scs\.venv\lib\site-packages (from requests->kagglehub) (3.20)
Requirement already satisfied: urllib3<3,>=1.26 in d:\college\own\ml\scs\.venv\lib\site-packages (from requests->kagglehub) (2.8.0)
Requirement already satisfied: certifi>=2023.5.7 in d:\college\own\ml\scs\.venv\lib\site-packages (from requests->kagglehub) (2026.7.22)
Requirement already satisfied: colorama in d:\college\own\ml\scs\.venv\lib\site-packages (from tqdm->kagglehub) (0.4.6)

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import kagglehub
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

print("Setup successful!")

Setup successful!

In [4]:
path = kagglehub.dataset_download("yasserh/titanic-dataset")

print("Dataset path:", path)

Dataset path: C:\Users\Lenovo\.cache\kagglehub\datasets\yasserh\titanic-dataset\versions\1

In [7]:
import os
import shutil
import kagglehub

# Download dataset
path = kagglehub.dataset_download("yasserh/titanic-dataset")

# Get current notebook/project folder
current_folder = os.getcwd()

# Copy all dataset files into current folder
for file in os.listdir(path):
    src = os.path.join(path, file)
    dst = os.path.join(current_folder, file)

    if os.path.isfile(src):
        shutil.copy2(src, dst)

print("Dataset copied to:", current_folder)
print("Files:", os.listdir(current_folder))

Dataset copied to: d:\college\own\ml\scs\week2\day1
Files: ['ford.csv', 'Titanic-Dataset.csv', 'titanic.ipynb']

In [8]:
import shutil

cache_path = r"C:\Users\Lenovo\.cache\kagglehub\datasets\yasserh\titanic-dataset"

shutil.rmtree(cache_path)

print("Kaggle cache deleted.")

Kaggle cache deleted.

In [17]:
df=pd.read_csv("Titanic-Dataset.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [15]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [41]:
df.drop(columns=['Ticket'], inplace=True)

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Name         891 non-null    str
 3   Sex          891 non-null    str
 4   Age          714 non-null    float64
 5   SibSp        891 non-null    int64
 6   Parch        891 non-null    int64
 7   Ticket       891 non-null    str
 8   Fare         891 non-null    float64
 9   Embarked     889 non-null    str
dtypes: float64(2), int64(4), str(4)
memory usage: 69.7 KB

In [25]:
df['Age'] = df['Age'].fillna(df['Age'].mean())

In [22]:
df.dropna(subset=['Embarked'], inplace=True)

In [26]:
df.info()

<class 'pandas.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  889 non-null    int64
 1   Survived     889 non-null    int64
 2   Name         889 non-null    str
 3   Sex          889 non-null    str
 4   Age          889 non-null    float64
 5   SibSp        889 non-null    int64
 6   Parch        889 non-null    int64
 7   Ticket       889 non-null    str
 8   Fare         889 non-null    float64
 9   Embarked     889 non-null    str
dtypes: float64(2), int64(4), str(4)
memory usage: 76.4 KB

In [28]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [32]:
df['Sex'] = le.fit_transform(df['Sex'])
df['Embarked'] = le.fit_transform(df['Embarked'])

In [33]:
df.head()

,PassengerId,Survived,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,"Braund, Mr. Owen Harris",1,22.0,1,0,A/5 21171,7.2500,2
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,38.0,1,0,PC 17599,71.2833,0
2,3,1,"Heikkinen, Miss. Laina",0,26.0,0,0,STON/O2. 3101282,7.9250,2
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,35.0,1,0,113803,53.1000,2
4,5,0,"Allen, Mr. William Henry",1,35.0,0,0,373450,8.0500,2

In [42]:
df.info()

<class 'pandas.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  889 non-null    int64
 1   Survived     889 non-null    int64
 2   Sex          889 non-null    int64
 3   Age          889 non-null    float64
 4   SibSp        889 non-null    int64
 5   Parch        889 non-null    int64
 6   Fare         889 non-null    float64
 7   Embarked     889 non-null    int64
dtypes: float64(2), int64(6)
memory usage: 62.5 KB

In [43]:
df = df.astype(int)

In [44]:
X = df.drop(columns=['Survived'])
y = df['Survived']

In [45]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [48]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [49]:
y_pred=model.predict(X_test)

In [50]:
y_pred

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1])

In [51]:
# evaluate the model
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
print("Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.7921348314606742
Confusion Matrix:
 [[90 19]
 [18 51]]
Classification Report:
               precision    recall  f1-score   support

           0       0.83      0.83      0.83       109
           1       0.73      0.74      0.73        69

    accuracy                           0.79       178
   macro avg       0.78      0.78      0.78       178
weighted avg       0.79      0.79      0.79       178

model tried= logistic regression
model2= knn

In [55]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
# X_train_scaled.head()

In [62]:
from sklearn.neighbors import KNeighborsClassifier
model_knn = KNeighborsClassifier(n_neighbors=25)

In [63]:
model_knn.fit(X_train_scaled, y_train)

KNeighborsClassifier(n_neighbors=25)

In [64]:
model_knn.predict(X_test_scaled)

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       1, 1])

In [65]:
y_pred_knn = model_knn.predict(X_test_scaled)

In [66]:
accuracy_knn = accuracy_score(y_test, y_pred_knn)
conf_matrix_knn = confusion_matrix(y_test, y_pred_knn)
accuracy_knn, conf_matrix_knn

(0.8033707865168539,
 array([[90, 19],
        [16, 53]]))

In [69]:
classification_report_knn = classification_report(y_test, y_pred_knn)
print(classification_report_knn)

              precision    recall  f1-score   support

           0       0.85      0.83      0.84       109
           1       0.74      0.77      0.75        69

    accuracy                           0.80       178
   macro avg       0.79      0.80      0.79       178
weighted avg       0.81      0.80      0.80       178